spring:
  application:
    name: tdd
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: toor
    driverClassName: org.h2.Driver
  jpa:
    database: h2
    database-plataform: org.hibernate.dialect.H2Dialect
    #apenas em dev
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true